---
- name: test latest version
  hosts: all
  vars: 
        app_path: ~/matthew-project0-production
  tasks:
          - name: install python3-venv
            package:
                    name: python3-venv
                    state: latest

          - name: install git
            package:
                    name: git
                    state: latest

          - name: install python
            package:
                    name: python3
                    state: latest


          - name: clone repo
            git:
                    repo: 'https://github.com/2105-may24-devops/matthew-project0.git' 
                    dest: '{{ app_path }}' 
          

          - name: venv setup 
            command: python3 -m venv '{{ app_path }}/venv'


          - name: resolve dependences
            pip:
                    
                    requirements: '{{ app_path }}/requirements.txt'

          
                        
        
