---
- name: delete application
  hosts: all
  tasks:
          - name: remove app
            ansible.builtin.file:
                    path: ~/matthew-project0-production
                    force: yes
                    state: absent
          - name: remove data
            ansible.builtin.file:
                    path: ~/project-data
                    force: yes
                    state: absent
          - name: remove logs
            ansible.builtin.file:
                    path: ~/test_log.txt
                    state: absent
          - name: remove logs
            ansible.builtin.file:
                    path: ~/error_logs.txt
                    state: absent
